import = ["~/.config/alacritty/themes/themes/papercolor_light.toml"]

[env]
TERM = "alacritty"

[font]
size = 15.0

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[scrolling]
history = 50000
multiplier = 3

[window]
dynamic_title = true
title = "term"

[window.dimensions]
columns = 120
lines = 60
